mode: inference_single # or 'inference_single' to inference on a single image
device: "sony" # iphone

model:
  loss_type: contextual
  file_type: RAW
  num_in_channel: 4
  num_out_channel: 3
  up_ratio: 4
  upsample_type: 'deconv'

io:
  inference_root: '/media/cecilia/EXT1/zoom/dslr_10x_both/'
  inference_path: '/media/cecilia/EXT1/zoom/dslr_10x_test/dslr_10x_both/00192/00006.ARW' # 00245 00186 00169 00101 00077
  fracx: 0.45
  fracy: 0.45
  prefix: -1-2
  save_root: '/media/cecilia/EXT1/zoom'
  restore_ckpt: '/media/cecilia/EXT1/zoom/experiments/bayer_syn/bayer_cont_x8_clean_camera' # core/rgb_x4_cont_coord_5_patch2_w5_camera_wb_cont #/bayer_syn/bayer_cont_x8_clean_camera/checkpoint
  task_folder: restore_resnet_syn_8x
