mode: inference # 'inference' or 'inference_single' to inference on a single image
device: 'sony' # iphone

model:
  loss_type: contextual
  file_type: RAW
  num_in_channel: 4
  num_out_channel: 3
  up_ratio: 4
  upsample_type: 'deconv'

io:
  inference_root: '/xxx/'  # if 'mode' is 'inference_single'
  inference_path: '/xxx/xxx.ARW' # if 'mode' is 'inference'
  fracx: 0.5  # x-fraciton of the cropped region, 0.5 would be the x-center
  fracy: 0.5  # y-fraciton of the cropped region, 0.5 would be the y-center
  save_root: '/xxx'
  restore_ckpt: '/xxx/model' # this folder contains checkpoint
  task_folder: restore_4x
